import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
// import Providers from "./providers";

// Custom Fonts
const gothic = localFont({
  src: [
    { path: "../public/fonts/Engravers' Gothic Regular.otf", weight: "400" },
    { path: "../public/fonts/Engravers' Gothic Regular.otf", weight: "700" },
  ],
  variable: "--font-gothic",
  display: "swap",
});

const alilato = localFont({
  src: [
    { path: "../public/fonts/fonnts.com-Alilato_Extra_Light.ttf", weight: "400" },
    { path: "../public/fonts/fonnts.com-Alilato_Extra_Light.ttf", weight: "600" },
  ],
  variable: "--font-alilato",
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothic.variable} ${alilato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
